CREATE TABLE role (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE
);


-- ================================
-- User Table
-- ================================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL
);

-- ================================
-- Join Table: user_roles
-- ================================
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
                                    ON DELETE CASCADE,
                            CONSTRAINT fk_role
                                FOREIGN KEY (role_id)
                                    REFERENCES role(id)
                                    ON DELETE CASCADE
);


-- ================================
-- Permission Table
-- ================================
CREATE TABLE permission (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL UNIQUE
);

-- ================================
-- Permission Group Table
-- ================================
CREATE TABLE permission_group (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(100) NOT NULL UNIQUE
);

-- ================================
-- Join Table: user_permission_groups
-- ================================
CREATE TABLE user_permission_groups
(
    user_id             BIGINT NOT NULL,
    permission_group_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, permission_group_id),
    CONSTRAINT fk_user_pg
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_pg
        FOREIGN KEY (permission_group_id)
            REFERENCES permission_group (id)
            ON DELETE CASCADE
);

-- ================================
-- Join Table (Many-To-Many)
-- ================================
CREATE TABLE permission_group_permissions (
                                              permission_group_id BIGINT NOT NULL,
                                              permission_id BIGINT NOT NULL,
                                              PRIMARY KEY (permission_group_id, permission_id),
                                              CONSTRAINT fk_pgid
                                                  FOREIGN KEY (permission_group_id)
                                                      REFERENCES permission_group(id)
                                                      ON DELETE CASCADE,
                                              CONSTRAINT fk_permission
                                                  FOREIGN KEY (permission_id)
                                                      REFERENCES permission(id)
                                                      ON DELETE CASCADE
);