-- ================================
-- Role Table
-- ================================

CREATE TABLE role (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE
);


-- ================================
-- User Table
-- ================================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password    VARCHAR(255) NOT NULL,
                       balance     BIGINT       NOT NULL,
                       pin         int     DEFAULT 0,
                       pin_enabled boolean DEFAULT FALSE,
                       is_Locked   boolean DEFAULT FALSE
);

-- ================================
-- Permission Table
-- ================================
CREATE TABLE permission (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL UNIQUE
);





-- ================================
-- Join Table: user_roles
-- ================================
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
                                    ON DELETE CASCADE,
                            CONSTRAINT fk_role
                                FOREIGN KEY (role_id)
                                    REFERENCES role(id)
                                    ON DELETE CASCADE
);






-- ================================
-- Join Table: role_permissions
-- ================================
CREATE TABLE role_permission
(
    role_id             BIGINT NOT NULL,
    permission_id       BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_pg
        FOREIGN KEY (role_id)
            REFERENCES role (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_pg
        FOREIGN KEY (permission_id)
            REFERENCES permission (id)
            ON DELETE CASCADE
);


