-- Erstellen der Kategorie-Tabelle
CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    image_Path VARCHAR(255)
);

-- Erstellen der Produkt-Tabelle
CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    anzeigename    VARCHAR(255) UNIQUE,
    vk             INT          NOT NULL, -- Preis in Cents (wie in deinem Code price / 100.0)
    image_Path VARCHAR(255),
    fk_category_id BIGINT       NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (fk_category_id) REFERENCES category (id)
);
