
INSERT INTO PERMISSION (NAME) values ('READ_JOBS');

INSERT INTO PERMISSION (NAME) values ('WRITE_JOBS');

INSERT INTO PERMISSION (NAME) values ('DELETE_JOBS');

INSERT INTO PERMISSION (NAME) values ('TRIGGER_JOBS');

