-- Erstellung der Fees-Tabelle
CREATE TABLE fees (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      amount INTEGER NOT NULL,
                      description VARCHAR(255) NOT NULL,
                      fee_type VARCHAR(50) NOT NULL, -- Speichert den Namen des Enums als String
                      created_at TIMESTAMP NOT NULL,

    -- Foreign Key Constraint zur User-Tabelle
                      CONSTRAINT fk_fees_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Index für Performance bei der Historien-Abfrage
CREATE INDEX idx_fees_user_created_at ON fees(user_id, created_at);