-- Tabelle für die ausgegebenen Kontingente
CREATE TABLE prepaid_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    giver_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    total_quantity INTEGER NOT NULL,
    remaining_quantity INTEGER NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_voucher_giver FOREIGN KEY (giver_id) REFERENCES users(id),
    CONSTRAINT fk_voucher_product FOREIGN KEY (product_id) REFERENCES product(id)
);

-- Index für schnelles Finden von verfügbaren Vouchern (FIFO Prinzip)
CREATE INDEX idx_voucher_lookup ON prepaid_vouchers (product_id, remaining_quantity, created_at);

-- Tabelle für die Dokumentation des Verzehrs
CREATE TABLE voucher_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    voucher_id BIGINT NOT NULL,
    consumer_id BIGINT NOT NULL,
    redeemed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_redemption_voucher FOREIGN KEY (voucher_id) REFERENCES prepaid_vouchers(id) ON DELETE CASCADE,
    CONSTRAINT fk_redemption_consumer FOREIGN KEY (consumer_id) REFERENCES users(id)
);