
INSERT INTO PERMISSION (NAME) values ('WRITE_SCHEDULED_FEES');
INSERT INTO PERMISSION (NAME) values ('READ_SCHEDULED_FEES');
INSERT INTO PERMISSION (NAME) values ('DELETE_SCHEDULED_FEES');

CREATE TABLE system_jobs (
    -- Basis-Felder (für alle Jobs)
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             job_type VARCHAR(31) NOT NULL, -- Diskriminator-Spalte
                             cron_expression VARCHAR(255) NOT NULL,
                             enabled BOOLEAN NOT NULL DEFAULT TRUE,

    -- ScheduledFeeJob Felder
                             amount_in_cents INTEGER,
                             description VARCHAR(255),
                             target_group_id BIGINT
);

